contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #mblabcallvariants channel"
    url: https://nfcore.slack.com/channels/mblabcallvariants
    about: Discussion about the nf-core/mblabcallvariants pipeline
