name: yaha_index
description: Create YAHA index for a reference genome
keywords:
  - index
  - fasta
  - genome
  - reference
tools:
  - yaha:
      description: "fast and flexible long-read alignment with optimal breakpoint detection"
      homepage: "https://github.com/GregoryFaust/yaha"
      documentation: "https://www.dropbox.com/s/7j758vpbaskcq20/YAHA_User_Guide.0.1.83.pdf?dl=0"
      tool_dev_url: "https://github.com/GregoryFaust/yaha"
      doi: "10.1093/bioinformatics/bts456"
      licence: "['MIT']"
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: Input genome fasta file
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - index:
      type: file
      description: YAHA genome index file
      pattern: "*.X15_01_65525S"
  - nib2:
      type: file
      description: YAHA compressed genome file
      pattern: "*.nib2"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@cmatkhan"
